sudo: false
language: python

addons:
  apt:
    packages:
    - redis-server

matrix:
  # major versions, test first
  include:
    - env: TOXENV=py27
    - env: TOXENV=py35-dev
      python: "3.5-dev"
env:
  # - TOXENV=py27
  # - TOXENV=py35-dev
  # other versions
  - TOXENV=py26
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  # not included, for incompatibility
  # - "2.5" # tarvis errs
  # - "3.2" # humanfriendly cant install
  # - "pypy3" # psutil errs

install:
  - pip install tox

# command to run tests
script: tox
