language: python
sudo: required
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install tcl8.5
  - wget http://download.redis.io/releases/redis-2.8.3.tar.gz
  - tar -xvzf redis-2.8.3.tar.gz
  - cd redis-2.8.3
  - make
  - sudo make install
  - cd ..
  # - apt-get install redis-server
install: 
  - "pip install -r requirements.txt"     
  - "pip install -e ."

# command to run tests
script: py.test
