language: python

addons:
  apt:
    packages:
    - redis-server

python:
  # - "2.5" # tarvis errs
  - "2.6"
  - "2.7"
  # - "3.2" # humanfriendly cant install
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypy"
  # - "pypy3" # psutil errs

install: 
  - "pip install --upgrade -r requirements.txt"     
  - "pip install -e ."

# command to run tests
script: py.test
