language: python
# cache: pip

addons:
  apt:
    packages:
    - redis-server

python:
  # major versions, test first
  - "2.7"
  - "3.5-dev"
  # other versions
  - "2.6"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  # not included, for incompatibility
  # - "2.5" # tarvis errs
  # - "3.2" # humanfriendly cant install
  # - "pypy3" # psutil errs

install: 
  - "pip install --upgrade -r requirements.txt"     
  - "pip install -e ."

# command to run tests
script: py.test -v  -k redis_fail_2
