sudo: false
language: python

addons:
  apt:
    packages:
    - redis-server
cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox


matrix:
  # add py35 and nightly
  include:
    - env: TOXENV=py35
      python: "3.5"
    - env: TOXENV=py
      python: "nightly"
env:
  # major versions first
  - TOXENV=py27
  - TOXENV=py34
  # - TOXENV=py35
  # other versions
  - TOXENV=py26
  - TOXENV=py33
  - TOXENV=pypy
  # not included, for incompatibility
  # - "2.5" # tarvis errs
  # - "3.2" # humanfriendly cant install
  # - "pypy3" # psutil errs

install:
  - pip install tox

# command to run tests
script: tox
